/**
 */
package org.emftrace.metamodel.TechnologySolutionModel.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.emftrace.metamodel.TechnologySolutionModel.util.TechnologySolutionModelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class TechnologySolutionModelItemProviderAdapterFactory extends TechnologySolutionModelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TechnologySolutionModelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolutionModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySolutionModelItemProvider technologySolutionModelItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolutionModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySolutionModelAdapter() {
		if (technologySolutionModelItemProvider == null) {
			technologySolutionModelItemProvider = new TechnologySolutionModelItemProvider(this);
		}

		return technologySolutionModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolutionCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySolutionCatalogItemProvider technologySolutionCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolutionCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySolutionCatalogAdapter() {
		if (technologySolutionCatalogItemProvider == null) {
			technologySolutionCatalogItemProvider = new TechnologySolutionCatalogItemProvider(this);
		}

		return technologySolutionCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeatureCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyFeatureCatalogItemProvider technologyFeatureCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeatureCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyFeatureCatalogAdapter() {
		if (technologyFeatureCatalogItemProvider == null) {
			technologyFeatureCatalogItemProvider = new TechnologyFeatureCatalogItemProvider(this);
		}

		return technologyFeatureCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.RelationCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationCatalogItemProvider relationCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.RelationCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationCatalogAdapter() {
		if (relationCatalogItemProvider == null) {
			relationCatalogItemProvider = new RelationCatalogItemProvider(this);
		}

		return relationCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.ASTACatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ASTACatalogItemProvider astaCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.ASTACatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createASTACatalogAdapter() {
		if (astaCatalogItemProvider == null) {
			astaCatalogItemProvider = new ASTACatalogItemProvider(this);
		}

		return astaCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.ConceptualSolutionCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConceptualSolutionCatalogItemProvider conceptualSolutionCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.ConceptualSolutionCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConceptualSolutionCatalogAdapter() {
		if (conceptualSolutionCatalogItemProvider == null) {
			conceptualSolutionCatalogItemProvider = new ConceptualSolutionCatalogItemProvider(this);
		}

		return conceptualSolutionCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.DevelopmentEnvironmentCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DevelopmentEnvironmentCatalogItemProvider developmentEnvironmentCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.DevelopmentEnvironmentCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDevelopmentEnvironmentCatalogAdapter() {
		if (developmentEnvironmentCatalogItemProvider == null) {
			developmentEnvironmentCatalogItemProvider = new DevelopmentEnvironmentCatalogItemProvider(this);
		}

		return developmentEnvironmentCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeatureEvaluationCatalog} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyFeatureEvaluationCatalogItemProvider technologyFeatureEvaluationCatalogItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeatureEvaluationCatalog}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyFeatureEvaluationCatalogAdapter() {
		if (technologyFeatureEvaluationCatalogItemProvider == null) {
			technologyFeatureEvaluationCatalogItemProvider = new TechnologyFeatureEvaluationCatalogItemProvider(this);
		}

		return technologyFeatureEvaluationCatalogItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolutions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySolutionsItemProvider technologySolutionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolutions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySolutionsAdapter() {
		if (technologySolutionsItemProvider == null) {
			technologySolutionsItemProvider = new TechnologySolutionsItemProvider(this);
		}

		return technologySolutionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySolutionItemProvider technologySolutionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologySolution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySolutionAdapter() {
		if (technologySolutionItemProvider == null) {
			technologySolutionItemProvider = new TechnologySolutionItemProvider(this);
		}

		return technologySolutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeature} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyFeatureItemProvider technologyFeatureItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyFeatureAdapter() {
		if (technologyFeatureItemProvider == null) {
			technologyFeatureItemProvider = new TechnologyFeatureItemProvider(this);
		}

		return technologyFeatureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeatureConcernMeasurement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyFeatureConcernMeasurementItemProvider technologyFeatureConcernMeasurementItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeatureConcernMeasurement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyFeatureConcernMeasurementAdapter() {
		if (technologyFeatureConcernMeasurementItemProvider == null) {
			technologyFeatureConcernMeasurementItemProvider = new TechnologyFeatureConcernMeasurementItemProvider(this);
		}

		return technologyFeatureConcernMeasurementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeaturesComparison} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyFeaturesComparisonItemProvider technologyFeaturesComparisonItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.TechnologyFeaturesComparison}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyFeaturesComparisonAdapter() {
		if (technologyFeaturesComparisonItemProvider == null) {
			technologyFeaturesComparisonItemProvider = new TechnologyFeaturesComparisonItemProvider(this);
		}

		return technologyFeaturesComparisonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.FeatureBasedBenefit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureBasedBenefitItemProvider featureBasedBenefitItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.FeatureBasedBenefit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureBasedBenefitAdapter() {
		if (featureBasedBenefitItemProvider == null) {
			featureBasedBenefitItemProvider = new FeatureBasedBenefitItemProvider(this);
		}

		return featureBasedBenefitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.ConcernBasedBenefit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConcernBasedBenefitItemProvider concernBasedBenefitItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.ConcernBasedBenefit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConcernBasedBenefitAdapter() {
		if (concernBasedBenefitItemProvider == null) {
			concernBasedBenefitItemProvider = new ConcernBasedBenefitItemProvider(this);
		}

		return concernBasedBenefitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.FeatureBasedDrawback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureBasedDrawbackItemProvider featureBasedDrawbackItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.FeatureBasedDrawback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureBasedDrawbackAdapter() {
		if (featureBasedDrawbackItemProvider == null) {
			featureBasedDrawbackItemProvider = new FeatureBasedDrawbackItemProvider(this);
		}

		return featureBasedDrawbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.ConcernBasedDrawback} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConcernBasedDrawbackItemProvider concernBasedDrawbackItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.ConcernBasedDrawback}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConcernBasedDrawbackAdapter() {
		if (concernBasedDrawbackItemProvider == null) {
			concernBasedDrawbackItemProvider = new ConcernBasedDrawbackItemProvider(this);
		}

		return concernBasedDrawbackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.ConceptualSolutions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConceptualSolutionsItemProvider conceptualSolutionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.ConceptualSolutions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConceptualSolutionsAdapter() {
		if (conceptualSolutionsItemProvider == null) {
			conceptualSolutionsItemProvider = new ConceptualSolutionsItemProvider(this);
		}

		return conceptualSolutionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.ConceptualSolution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConceptualSolutionItemProvider conceptualSolutionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.ConceptualSolution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConceptualSolutionAdapter() {
		if (conceptualSolutionItemProvider == null) {
			conceptualSolutionItemProvider = new ConceptualSolutionItemProvider(this);
		}

		return conceptualSolutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.DevelopmentEnvironments} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DevelopmentEnvironmentsItemProvider developmentEnvironmentsItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.DevelopmentEnvironments}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDevelopmentEnvironmentsAdapter() {
		if (developmentEnvironmentsItemProvider == null) {
			developmentEnvironmentsItemProvider = new DevelopmentEnvironmentsItemProvider(this);
		}

		return developmentEnvironmentsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.DevelopmentEnvironment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DevelopmentEnvironmentItemProvider developmentEnvironmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.DevelopmentEnvironment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDevelopmentEnvironmentAdapter() {
		if (developmentEnvironmentItemProvider == null) {
			developmentEnvironmentItemProvider = new DevelopmentEnvironmentItemProvider(this);
		}

		return developmentEnvironmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.Relations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationsItemProvider relationsItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.Relations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationsAdapter() {
		if (relationsItemProvider == null) {
			relationsItemProvider = new RelationsItemProvider(this);
		}

		return relationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.TechnologySolutionModel.Relation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationItemProvider relationItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.TechnologySolutionModel.Relation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationAdapter() {
		if (relationItemProvider == null) {
			relationItemProvider = new RelationItemProvider(this);
		}

		return relationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (technologySolutionModelItemProvider != null) technologySolutionModelItemProvider.dispose();
		if (technologySolutionCatalogItemProvider != null) technologySolutionCatalogItemProvider.dispose();
		if (technologyFeatureCatalogItemProvider != null) technologyFeatureCatalogItemProvider.dispose();
		if (relationCatalogItemProvider != null) relationCatalogItemProvider.dispose();
		if (astaCatalogItemProvider != null) astaCatalogItemProvider.dispose();
		if (conceptualSolutionCatalogItemProvider != null) conceptualSolutionCatalogItemProvider.dispose();
		if (developmentEnvironmentCatalogItemProvider != null) developmentEnvironmentCatalogItemProvider.dispose();
		if (technologyFeatureEvaluationCatalogItemProvider != null) technologyFeatureEvaluationCatalogItemProvider.dispose();
		if (technologySolutionsItemProvider != null) technologySolutionsItemProvider.dispose();
		if (technologySolutionItemProvider != null) technologySolutionItemProvider.dispose();
		if (technologyFeatureItemProvider != null) technologyFeatureItemProvider.dispose();
		if (technologyFeatureConcernMeasurementItemProvider != null) technologyFeatureConcernMeasurementItemProvider.dispose();
		if (technologyFeaturesComparisonItemProvider != null) technologyFeaturesComparisonItemProvider.dispose();
		if (featureBasedBenefitItemProvider != null) featureBasedBenefitItemProvider.dispose();
		if (concernBasedBenefitItemProvider != null) concernBasedBenefitItemProvider.dispose();
		if (featureBasedDrawbackItemProvider != null) featureBasedDrawbackItemProvider.dispose();
		if (concernBasedDrawbackItemProvider != null) concernBasedDrawbackItemProvider.dispose();
		if (conceptualSolutionsItemProvider != null) conceptualSolutionsItemProvider.dispose();
		if (conceptualSolutionItemProvider != null) conceptualSolutionItemProvider.dispose();
		if (developmentEnvironmentsItemProvider != null) developmentEnvironmentsItemProvider.dispose();
		if (developmentEnvironmentItemProvider != null) developmentEnvironmentItemProvider.dispose();
		if (relationsItemProvider != null) relationsItemProvider.dispose();
		if (relationItemProvider != null) relationItemProvider.dispose();
	}

}
