/**
 */
package org.emftrace.metamodel.OWLModel.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.emftrace.metamodel.OWLModel.util.OWLModelAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class OWLModelItemProviderAdapterFactory extends OWLModelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OWLModelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.AbbreviatedIRI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbbreviatedIRIItemProvider abbreviatedIRIItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.AbbreviatedIRI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAbbreviatedIRIAdapter() {
		if (abbreviatedIRIItemProvider == null) {
			abbreviatedIRIItemProvider = new AbbreviatedIRIItemProvider(this);
		}

		return abbreviatedIRIItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Annotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationItemProvider annotationItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Annotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationAdapter() {
		if (annotationItemProvider == null) {
			annotationItemProvider = new AnnotationItemProvider(this);
		}

		return annotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.AnnotationAssertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationAssertionItemProvider annotationAssertionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.AnnotationAssertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationAssertionAdapter() {
		if (annotationAssertionItemProvider == null) {
			annotationAssertionItemProvider = new AnnotationAssertionItemProvider(this);
		}

		return annotationAssertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.AnnotationProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationPropertyItemProvider annotationPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.AnnotationProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationPropertyAdapter() {
		if (annotationPropertyItemProvider == null) {
			annotationPropertyItemProvider = new AnnotationPropertyItemProvider(this);
		}

		return annotationPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.AnnotationPropertyDomain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationPropertyDomainItemProvider annotationPropertyDomainItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.AnnotationPropertyDomain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationPropertyDomainAdapter() {
		if (annotationPropertyDomainItemProvider == null) {
			annotationPropertyDomainItemProvider = new AnnotationPropertyDomainItemProvider(this);
		}

		return annotationPropertyDomainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.AnnotationPropertyRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationPropertyRangeItemProvider annotationPropertyRangeItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.AnnotationPropertyRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationPropertyRangeAdapter() {
		if (annotationPropertyRangeItemProvider == null) {
			annotationPropertyRangeItemProvider = new AnnotationPropertyRangeItemProvider(this);
		}

		return annotationPropertyRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.AnonymousIndividual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnonymousIndividualItemProvider anonymousIndividualItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.AnonymousIndividual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnonymousIndividualAdapter() {
		if (anonymousIndividualItemProvider == null) {
			anonymousIndividualItemProvider = new AnonymousIndividualItemProvider(this);
		}

		return anonymousIndividualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.AsymmetricObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AsymmetricObjectPropertyItemProvider asymmetricObjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.AsymmetricObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAsymmetricObjectPropertyAdapter() {
		if (asymmetricObjectPropertyItemProvider == null) {
			asymmetricObjectPropertyItemProvider = new AsymmetricObjectPropertyItemProvider(this);
		}

		return asymmetricObjectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Class} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassItemProvider classItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Class}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassAdapter() {
		if (classItemProvider == null) {
			classItemProvider = new ClassItemProvider(this);
		}

		return classItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ClassAssertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassAssertionItemProvider classAssertionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ClassAssertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassAssertionAdapter() {
		if (classAssertionItemProvider == null) {
			classAssertionItemProvider = new ClassAssertionItemProvider(this);
		}

		return classAssertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataAllValuesFrom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataAllValuesFromItemProvider dataAllValuesFromItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataAllValuesFrom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataAllValuesFromAdapter() {
		if (dataAllValuesFromItemProvider == null) {
			dataAllValuesFromItemProvider = new DataAllValuesFromItemProvider(this);
		}

		return dataAllValuesFromItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataComplementOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataComplementOfItemProvider dataComplementOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataComplementOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataComplementOfAdapter() {
		if (dataComplementOfItemProvider == null) {
			dataComplementOfItemProvider = new DataComplementOfItemProvider(this);
		}

		return dataComplementOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataExactCardinality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataExactCardinalityItemProvider dataExactCardinalityItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataExactCardinality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataExactCardinalityAdapter() {
		if (dataExactCardinalityItemProvider == null) {
			dataExactCardinalityItemProvider = new DataExactCardinalityItemProvider(this);
		}

		return dataExactCardinalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataHasValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataHasValueItemProvider dataHasValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataHasValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataHasValueAdapter() {
		if (dataHasValueItemProvider == null) {
			dataHasValueItemProvider = new DataHasValueItemProvider(this);
		}

		return dataHasValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataIntersectionOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataIntersectionOfItemProvider dataIntersectionOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataIntersectionOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataIntersectionOfAdapter() {
		if (dataIntersectionOfItemProvider == null) {
			dataIntersectionOfItemProvider = new DataIntersectionOfItemProvider(this);
		}

		return dataIntersectionOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataMaxCardinality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataMaxCardinalityItemProvider dataMaxCardinalityItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataMaxCardinality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataMaxCardinalityAdapter() {
		if (dataMaxCardinalityItemProvider == null) {
			dataMaxCardinalityItemProvider = new DataMaxCardinalityItemProvider(this);
		}

		return dataMaxCardinalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataMinCardinality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataMinCardinalityItemProvider dataMinCardinalityItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataMinCardinality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataMinCardinalityAdapter() {
		if (dataMinCardinalityItemProvider == null) {
			dataMinCardinalityItemProvider = new DataMinCardinalityItemProvider(this);
		}

		return dataMinCardinalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataOneOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataOneOfItemProvider dataOneOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataOneOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataOneOfAdapter() {
		if (dataOneOfItemProvider == null) {
			dataOneOfItemProvider = new DataOneOfItemProvider(this);
		}

		return dataOneOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPropertyItemProvider dataPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPropertyAdapter() {
		if (dataPropertyItemProvider == null) {
			dataPropertyItemProvider = new DataPropertyItemProvider(this);
		}

		return dataPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataPropertyAssertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPropertyAssertionItemProvider dataPropertyAssertionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataPropertyAssertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPropertyAssertionAdapter() {
		if (dataPropertyAssertionItemProvider == null) {
			dataPropertyAssertionItemProvider = new DataPropertyAssertionItemProvider(this);
		}

		return dataPropertyAssertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataPropertyDomain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPropertyDomainItemProvider dataPropertyDomainItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataPropertyDomain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPropertyDomainAdapter() {
		if (dataPropertyDomainItemProvider == null) {
			dataPropertyDomainItemProvider = new DataPropertyDomainItemProvider(this);
		}

		return dataPropertyDomainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataPropertyRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPropertyRangeItemProvider dataPropertyRangeItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataPropertyRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPropertyRangeAdapter() {
		if (dataPropertyRangeItemProvider == null) {
			dataPropertyRangeItemProvider = new DataPropertyRangeItemProvider(this);
		}

		return dataPropertyRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataSomeValuesFrom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataSomeValuesFromItemProvider dataSomeValuesFromItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataSomeValuesFrom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataSomeValuesFromAdapter() {
		if (dataSomeValuesFromItemProvider == null) {
			dataSomeValuesFromItemProvider = new DataSomeValuesFromItemProvider(this);
		}

		return dataSomeValuesFromItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Datatype} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeItemProvider datatypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Datatype}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeAdapter() {
		if (datatypeItemProvider == null) {
			datatypeItemProvider = new DatatypeItemProvider(this);
		}

		return datatypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DatatypeDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionItemProvider datatypeDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DatatypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionAdapter() {
		if (datatypeDefinitionItemProvider == null) {
			datatypeDefinitionItemProvider = new DatatypeDefinitionItemProvider(this);
		}

		return datatypeDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DatatypeRestriction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeRestrictionItemProvider datatypeRestrictionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DatatypeRestriction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeRestrictionAdapter() {
		if (datatypeRestrictionItemProvider == null) {
			datatypeRestrictionItemProvider = new DatatypeRestrictionItemProvider(this);
		}

		return datatypeRestrictionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DataUnionOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataUnionOfItemProvider dataUnionOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DataUnionOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataUnionOfAdapter() {
		if (dataUnionOfItemProvider == null) {
			dataUnionOfItemProvider = new DataUnionOfItemProvider(this);
		}

		return dataUnionOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Declaration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeclarationItemProvider declarationItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Declaration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeclarationAdapter() {
		if (declarationItemProvider == null) {
			declarationItemProvider = new DeclarationItemProvider(this);
		}

		return declarationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DifferentIndividuals} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DifferentIndividualsItemProvider differentIndividualsItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DifferentIndividuals}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDifferentIndividualsAdapter() {
		if (differentIndividualsItemProvider == null) {
			differentIndividualsItemProvider = new DifferentIndividualsItemProvider(this);
		}

		return differentIndividualsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DisjointClasses} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisjointClassesItemProvider disjointClassesItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DisjointClasses}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisjointClassesAdapter() {
		if (disjointClassesItemProvider == null) {
			disjointClassesItemProvider = new DisjointClassesItemProvider(this);
		}

		return disjointClassesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DisjointDataProperties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisjointDataPropertiesItemProvider disjointDataPropertiesItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DisjointDataProperties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisjointDataPropertiesAdapter() {
		if (disjointDataPropertiesItemProvider == null) {
			disjointDataPropertiesItemProvider = new DisjointDataPropertiesItemProvider(this);
		}

		return disjointDataPropertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DisjointObjectProperties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisjointObjectPropertiesItemProvider disjointObjectPropertiesItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DisjointObjectProperties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisjointObjectPropertiesAdapter() {
		if (disjointObjectPropertiesItemProvider == null) {
			disjointObjectPropertiesItemProvider = new DisjointObjectPropertiesItemProvider(this);
		}

		return disjointObjectPropertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.DisjointUnion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DisjointUnionItemProvider disjointUnionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.DisjointUnion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDisjointUnionAdapter() {
		if (disjointUnionItemProvider == null) {
			disjointUnionItemProvider = new DisjointUnionItemProvider(this);
		}

		return disjointUnionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.EquivalentClasses} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EquivalentClassesItemProvider equivalentClassesItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.EquivalentClasses}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEquivalentClassesAdapter() {
		if (equivalentClassesItemProvider == null) {
			equivalentClassesItemProvider = new EquivalentClassesItemProvider(this);
		}

		return equivalentClassesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.EquivalentDataProperties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EquivalentDataPropertiesItemProvider equivalentDataPropertiesItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.EquivalentDataProperties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEquivalentDataPropertiesAdapter() {
		if (equivalentDataPropertiesItemProvider == null) {
			equivalentDataPropertiesItemProvider = new EquivalentDataPropertiesItemProvider(this);
		}

		return equivalentDataPropertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.EquivalentObjectProperties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EquivalentObjectPropertiesItemProvider equivalentObjectPropertiesItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.EquivalentObjectProperties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEquivalentObjectPropertiesAdapter() {
		if (equivalentObjectPropertiesItemProvider == null) {
			equivalentObjectPropertiesItemProvider = new EquivalentObjectPropertiesItemProvider(this);
		}

		return equivalentObjectPropertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.FacetRestriction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FacetRestrictionItemProvider facetRestrictionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.FacetRestriction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFacetRestrictionAdapter() {
		if (facetRestrictionItemProvider == null) {
			facetRestrictionItemProvider = new FacetRestrictionItemProvider(this);
		}

		return facetRestrictionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.FunctionalDataProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionalDataPropertyItemProvider functionalDataPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.FunctionalDataProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionalDataPropertyAdapter() {
		if (functionalDataPropertyItemProvider == null) {
			functionalDataPropertyItemProvider = new FunctionalDataPropertyItemProvider(this);
		}

		return functionalDataPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.FunctionalObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionalObjectPropertyItemProvider functionalObjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.FunctionalObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionalObjectPropertyAdapter() {
		if (functionalObjectPropertyItemProvider == null) {
			functionalObjectPropertyItemProvider = new FunctionalObjectPropertyItemProvider(this);
		}

		return functionalObjectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.HasKey} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasKeyItemProvider hasKeyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.HasKey}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasKeyAdapter() {
		if (hasKeyItemProvider == null) {
			hasKeyItemProvider = new HasKeyItemProvider(this);
		}

		return hasKeyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.InverseFunctionalObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InverseFunctionalObjectPropertyItemProvider inverseFunctionalObjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.InverseFunctionalObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInverseFunctionalObjectPropertyAdapter() {
		if (inverseFunctionalObjectPropertyItemProvider == null) {
			inverseFunctionalObjectPropertyItemProvider = new InverseFunctionalObjectPropertyItemProvider(this);
		}

		return inverseFunctionalObjectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.InverseObjectProperties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InverseObjectPropertiesItemProvider inverseObjectPropertiesItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.InverseObjectProperties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInverseObjectPropertiesAdapter() {
		if (inverseObjectPropertiesItemProvider == null) {
			inverseObjectPropertiesItemProvider = new InverseObjectPropertiesItemProvider(this);
		}

		return inverseObjectPropertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.IRI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IRIItemProvider iriItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.IRI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIRIAdapter() {
		if (iriItemProvider == null) {
			iriItemProvider = new IRIItemProvider(this);
		}

		return iriItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.IrreflexiveObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IrreflexiveObjectPropertyItemProvider irreflexiveObjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.IrreflexiveObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIrreflexiveObjectPropertyAdapter() {
		if (irreflexiveObjectPropertyItemProvider == null) {
			irreflexiveObjectPropertyItemProvider = new IrreflexiveObjectPropertyItemProvider(this);
		}

		return irreflexiveObjectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Literal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LiteralItemProvider literalItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Literal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLiteralAdapter() {
		if (literalItemProvider == null) {
			literalItemProvider = new LiteralItemProvider(this);
		}

		return literalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.NamedIndividual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedIndividualItemProvider namedIndividualItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.NamedIndividual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedIndividualAdapter() {
		if (namedIndividualItemProvider == null) {
			namedIndividualItemProvider = new NamedIndividualItemProvider(this);
		}

		return namedIndividualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.NegativeDataPropertyAssertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeDataPropertyAssertionItemProvider negativeDataPropertyAssertionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.NegativeDataPropertyAssertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeDataPropertyAssertionAdapter() {
		if (negativeDataPropertyAssertionItemProvider == null) {
			negativeDataPropertyAssertionItemProvider = new NegativeDataPropertyAssertionItemProvider(this);
		}

		return negativeDataPropertyAssertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.NegativeObjectPropertyAssertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegativeObjectPropertyAssertionItemProvider negativeObjectPropertyAssertionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.NegativeObjectPropertyAssertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegativeObjectPropertyAssertionAdapter() {
		if (negativeObjectPropertyAssertionItemProvider == null) {
			negativeObjectPropertyAssertionItemProvider = new NegativeObjectPropertyAssertionItemProvider(this);
		}

		return negativeObjectPropertyAssertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectAllValuesFrom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectAllValuesFromItemProvider objectAllValuesFromItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectAllValuesFrom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectAllValuesFromAdapter() {
		if (objectAllValuesFromItemProvider == null) {
			objectAllValuesFromItemProvider = new ObjectAllValuesFromItemProvider(this);
		}

		return objectAllValuesFromItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectComplementOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectComplementOfItemProvider objectComplementOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectComplementOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectComplementOfAdapter() {
		if (objectComplementOfItemProvider == null) {
			objectComplementOfItemProvider = new ObjectComplementOfItemProvider(this);
		}

		return objectComplementOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectExactCardinality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectExactCardinalityItemProvider objectExactCardinalityItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectExactCardinality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectExactCardinalityAdapter() {
		if (objectExactCardinalityItemProvider == null) {
			objectExactCardinalityItemProvider = new ObjectExactCardinalityItemProvider(this);
		}

		return objectExactCardinalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectHasSelf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectHasSelfItemProvider objectHasSelfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectHasSelf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectHasSelfAdapter() {
		if (objectHasSelfItemProvider == null) {
			objectHasSelfItemProvider = new ObjectHasSelfItemProvider(this);
		}

		return objectHasSelfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectHasValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectHasValueItemProvider objectHasValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectHasValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectHasValueAdapter() {
		if (objectHasValueItemProvider == null) {
			objectHasValueItemProvider = new ObjectHasValueItemProvider(this);
		}

		return objectHasValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectIntersectionOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectIntersectionOfItemProvider objectIntersectionOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectIntersectionOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectIntersectionOfAdapter() {
		if (objectIntersectionOfItemProvider == null) {
			objectIntersectionOfItemProvider = new ObjectIntersectionOfItemProvider(this);
		}

		return objectIntersectionOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectInverseOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectInverseOfItemProvider objectInverseOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectInverseOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectInverseOfAdapter() {
		if (objectInverseOfItemProvider == null) {
			objectInverseOfItemProvider = new ObjectInverseOfItemProvider(this);
		}

		return objectInverseOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectMaxCardinality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectMaxCardinalityItemProvider objectMaxCardinalityItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectMaxCardinality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectMaxCardinalityAdapter() {
		if (objectMaxCardinalityItemProvider == null) {
			objectMaxCardinalityItemProvider = new ObjectMaxCardinalityItemProvider(this);
		}

		return objectMaxCardinalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectMinCardinality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectMinCardinalityItemProvider objectMinCardinalityItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectMinCardinality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectMinCardinalityAdapter() {
		if (objectMinCardinalityItemProvider == null) {
			objectMinCardinalityItemProvider = new ObjectMinCardinalityItemProvider(this);
		}

		return objectMinCardinalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectOneOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectOneOfItemProvider objectOneOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectOneOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectOneOfAdapter() {
		if (objectOneOfItemProvider == null) {
			objectOneOfItemProvider = new ObjectOneOfItemProvider(this);
		}

		return objectOneOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectPropertyItemProvider objectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectPropertyAdapter() {
		if (objectPropertyItemProvider == null) {
			objectPropertyItemProvider = new ObjectPropertyItemProvider(this);
		}

		return objectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectPropertyAssertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectPropertyAssertionItemProvider objectPropertyAssertionItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectPropertyAssertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectPropertyAssertionAdapter() {
		if (objectPropertyAssertionItemProvider == null) {
			objectPropertyAssertionItemProvider = new ObjectPropertyAssertionItemProvider(this);
		}

		return objectPropertyAssertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectPropertyChain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectPropertyChainItemProvider objectPropertyChainItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectPropertyChain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectPropertyChainAdapter() {
		if (objectPropertyChainItemProvider == null) {
			objectPropertyChainItemProvider = new ObjectPropertyChainItemProvider(this);
		}

		return objectPropertyChainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectPropertyDomain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectPropertyDomainItemProvider objectPropertyDomainItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectPropertyDomain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectPropertyDomainAdapter() {
		if (objectPropertyDomainItemProvider == null) {
			objectPropertyDomainItemProvider = new ObjectPropertyDomainItemProvider(this);
		}

		return objectPropertyDomainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectPropertyRange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectPropertyRangeItemProvider objectPropertyRangeItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectPropertyRange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectPropertyRangeAdapter() {
		if (objectPropertyRangeItemProvider == null) {
			objectPropertyRangeItemProvider = new ObjectPropertyRangeItemProvider(this);
		}

		return objectPropertyRangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectSomeValuesFrom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectSomeValuesFromItemProvider objectSomeValuesFromItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectSomeValuesFrom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectSomeValuesFromAdapter() {
		if (objectSomeValuesFromItemProvider == null) {
			objectSomeValuesFromItemProvider = new ObjectSomeValuesFromItemProvider(this);
		}

		return objectSomeValuesFromItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ObjectUnionOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectUnionOfItemProvider objectUnionOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ObjectUnionOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectUnionOfAdapter() {
		if (objectUnionOfItemProvider == null) {
			objectUnionOfItemProvider = new ObjectUnionOfItemProvider(this);
		}

		return objectUnionOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Ontology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OntologyItemProvider ontologyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Ontology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOntologyAdapter() {
		if (ontologyItemProvider == null) {
			ontologyItemProvider = new OntologyItemProvider(this);
		}

		return ontologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.Prefix} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrefixItemProvider prefixItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.Prefix}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrefixAdapter() {
		if (prefixItemProvider == null) {
			prefixItemProvider = new PrefixItemProvider(this);
		}

		return prefixItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.ReflexiveObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReflexiveObjectPropertyItemProvider reflexiveObjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.ReflexiveObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReflexiveObjectPropertyAdapter() {
		if (reflexiveObjectPropertyItemProvider == null) {
			reflexiveObjectPropertyItemProvider = new ReflexiveObjectPropertyItemProvider(this);
		}

		return reflexiveObjectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.SameIndividual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SameIndividualItemProvider sameIndividualItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.SameIndividual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSameIndividualAdapter() {
		if (sameIndividualItemProvider == null) {
			sameIndividualItemProvider = new SameIndividualItemProvider(this);
		}

		return sameIndividualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.SubAnnotationPropertyOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubAnnotationPropertyOfItemProvider subAnnotationPropertyOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.SubAnnotationPropertyOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubAnnotationPropertyOfAdapter() {
		if (subAnnotationPropertyOfItemProvider == null) {
			subAnnotationPropertyOfItemProvider = new SubAnnotationPropertyOfItemProvider(this);
		}

		return subAnnotationPropertyOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.SubClassOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubClassOfItemProvider subClassOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.SubClassOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubClassOfAdapter() {
		if (subClassOfItemProvider == null) {
			subClassOfItemProvider = new SubClassOfItemProvider(this);
		}

		return subClassOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.SubDataPropertyOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubDataPropertyOfItemProvider subDataPropertyOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.SubDataPropertyOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubDataPropertyOfAdapter() {
		if (subDataPropertyOfItemProvider == null) {
			subDataPropertyOfItemProvider = new SubDataPropertyOfItemProvider(this);
		}

		return subDataPropertyOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.SubObjectPropertyOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubObjectPropertyOfItemProvider subObjectPropertyOfItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.SubObjectPropertyOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubObjectPropertyOfAdapter() {
		if (subObjectPropertyOfItemProvider == null) {
			subObjectPropertyOfItemProvider = new SubObjectPropertyOfItemProvider(this);
		}

		return subObjectPropertyOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.SymmetricObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SymmetricObjectPropertyItemProvider symmetricObjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.SymmetricObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSymmetricObjectPropertyAdapter() {
		if (symmetricObjectPropertyItemProvider == null) {
			symmetricObjectPropertyItemProvider = new SymmetricObjectPropertyItemProvider(this);
		}

		return symmetricObjectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.emftrace.metamodel.OWLModel.TransitiveObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitiveObjectPropertyItemProvider transitiveObjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link org.emftrace.metamodel.OWLModel.TransitiveObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitiveObjectPropertyAdapter() {
		if (transitiveObjectPropertyItemProvider == null) {
			transitiveObjectPropertyItemProvider = new TransitiveObjectPropertyItemProvider(this);
		}

		return transitiveObjectPropertyItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (abbreviatedIRIItemProvider != null) abbreviatedIRIItemProvider.dispose();
		if (annotationItemProvider != null) annotationItemProvider.dispose();
		if (annotationAssertionItemProvider != null) annotationAssertionItemProvider.dispose();
		if (annotationPropertyItemProvider != null) annotationPropertyItemProvider.dispose();
		if (annotationPropertyDomainItemProvider != null) annotationPropertyDomainItemProvider.dispose();
		if (annotationPropertyRangeItemProvider != null) annotationPropertyRangeItemProvider.dispose();
		if (anonymousIndividualItemProvider != null) anonymousIndividualItemProvider.dispose();
		if (asymmetricObjectPropertyItemProvider != null) asymmetricObjectPropertyItemProvider.dispose();
		if (classItemProvider != null) classItemProvider.dispose();
		if (classAssertionItemProvider != null) classAssertionItemProvider.dispose();
		if (dataAllValuesFromItemProvider != null) dataAllValuesFromItemProvider.dispose();
		if (dataComplementOfItemProvider != null) dataComplementOfItemProvider.dispose();
		if (dataExactCardinalityItemProvider != null) dataExactCardinalityItemProvider.dispose();
		if (dataHasValueItemProvider != null) dataHasValueItemProvider.dispose();
		if (dataIntersectionOfItemProvider != null) dataIntersectionOfItemProvider.dispose();
		if (dataMaxCardinalityItemProvider != null) dataMaxCardinalityItemProvider.dispose();
		if (dataMinCardinalityItemProvider != null) dataMinCardinalityItemProvider.dispose();
		if (dataOneOfItemProvider != null) dataOneOfItemProvider.dispose();
		if (dataPropertyItemProvider != null) dataPropertyItemProvider.dispose();
		if (dataPropertyAssertionItemProvider != null) dataPropertyAssertionItemProvider.dispose();
		if (dataPropertyDomainItemProvider != null) dataPropertyDomainItemProvider.dispose();
		if (dataPropertyRangeItemProvider != null) dataPropertyRangeItemProvider.dispose();
		if (dataSomeValuesFromItemProvider != null) dataSomeValuesFromItemProvider.dispose();
		if (datatypeItemProvider != null) datatypeItemProvider.dispose();
		if (datatypeDefinitionItemProvider != null) datatypeDefinitionItemProvider.dispose();
		if (datatypeRestrictionItemProvider != null) datatypeRestrictionItemProvider.dispose();
		if (dataUnionOfItemProvider != null) dataUnionOfItemProvider.dispose();
		if (declarationItemProvider != null) declarationItemProvider.dispose();
		if (differentIndividualsItemProvider != null) differentIndividualsItemProvider.dispose();
		if (disjointClassesItemProvider != null) disjointClassesItemProvider.dispose();
		if (disjointDataPropertiesItemProvider != null) disjointDataPropertiesItemProvider.dispose();
		if (disjointObjectPropertiesItemProvider != null) disjointObjectPropertiesItemProvider.dispose();
		if (disjointUnionItemProvider != null) disjointUnionItemProvider.dispose();
		if (equivalentClassesItemProvider != null) equivalentClassesItemProvider.dispose();
		if (equivalentDataPropertiesItemProvider != null) equivalentDataPropertiesItemProvider.dispose();
		if (equivalentObjectPropertiesItemProvider != null) equivalentObjectPropertiesItemProvider.dispose();
		if (facetRestrictionItemProvider != null) facetRestrictionItemProvider.dispose();
		if (functionalDataPropertyItemProvider != null) functionalDataPropertyItemProvider.dispose();
		if (functionalObjectPropertyItemProvider != null) functionalObjectPropertyItemProvider.dispose();
		if (hasKeyItemProvider != null) hasKeyItemProvider.dispose();
		if (importItemProvider != null) importItemProvider.dispose();
		if (inverseFunctionalObjectPropertyItemProvider != null) inverseFunctionalObjectPropertyItemProvider.dispose();
		if (inverseObjectPropertiesItemProvider != null) inverseObjectPropertiesItemProvider.dispose();
		if (iriItemProvider != null) iriItemProvider.dispose();
		if (irreflexiveObjectPropertyItemProvider != null) irreflexiveObjectPropertyItemProvider.dispose();
		if (literalItemProvider != null) literalItemProvider.dispose();
		if (namedIndividualItemProvider != null) namedIndividualItemProvider.dispose();
		if (negativeDataPropertyAssertionItemProvider != null) negativeDataPropertyAssertionItemProvider.dispose();
		if (negativeObjectPropertyAssertionItemProvider != null) negativeObjectPropertyAssertionItemProvider.dispose();
		if (objectAllValuesFromItemProvider != null) objectAllValuesFromItemProvider.dispose();
		if (objectComplementOfItemProvider != null) objectComplementOfItemProvider.dispose();
		if (objectExactCardinalityItemProvider != null) objectExactCardinalityItemProvider.dispose();
		if (objectHasSelfItemProvider != null) objectHasSelfItemProvider.dispose();
		if (objectHasValueItemProvider != null) objectHasValueItemProvider.dispose();
		if (objectIntersectionOfItemProvider != null) objectIntersectionOfItemProvider.dispose();
		if (objectInverseOfItemProvider != null) objectInverseOfItemProvider.dispose();
		if (objectMaxCardinalityItemProvider != null) objectMaxCardinalityItemProvider.dispose();
		if (objectMinCardinalityItemProvider != null) objectMinCardinalityItemProvider.dispose();
		if (objectOneOfItemProvider != null) objectOneOfItemProvider.dispose();
		if (objectPropertyItemProvider != null) objectPropertyItemProvider.dispose();
		if (objectPropertyAssertionItemProvider != null) objectPropertyAssertionItemProvider.dispose();
		if (objectPropertyChainItemProvider != null) objectPropertyChainItemProvider.dispose();
		if (objectPropertyDomainItemProvider != null) objectPropertyDomainItemProvider.dispose();
		if (objectPropertyRangeItemProvider != null) objectPropertyRangeItemProvider.dispose();
		if (objectSomeValuesFromItemProvider != null) objectSomeValuesFromItemProvider.dispose();
		if (objectUnionOfItemProvider != null) objectUnionOfItemProvider.dispose();
		if (ontologyItemProvider != null) ontologyItemProvider.dispose();
		if (prefixItemProvider != null) prefixItemProvider.dispose();
		if (reflexiveObjectPropertyItemProvider != null) reflexiveObjectPropertyItemProvider.dispose();
		if (sameIndividualItemProvider != null) sameIndividualItemProvider.dispose();
		if (subAnnotationPropertyOfItemProvider != null) subAnnotationPropertyOfItemProvider.dispose();
		if (subClassOfItemProvider != null) subClassOfItemProvider.dispose();
		if (subDataPropertyOfItemProvider != null) subDataPropertyOfItemProvider.dispose();
		if (subObjectPropertyOfItemProvider != null) subObjectPropertyOfItemProvider.dispose();
		if (symmetricObjectPropertyItemProvider != null) symmetricObjectPropertyItemProvider.dispose();
		if (transitiveObjectPropertyItemProvider != null) transitiveObjectPropertyItemProvider.dispose();
	}

}
